// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from "./types";

// Use environment variables (ensure they are prefixed with VITE_ for Vite projects)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// DEBUG: Log environment variables at runtime
console.log("Supabase Client Init: VITE_SUPABASE_URL =", supabaseUrl);
console.log("Supabase Client Init: VITE_SUPABASE_ANON_KEY =", supabaseAnonKey ? 'Exists' : 'MISSING or undefined'); // Don't log the key itself

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Supabase Client Init Error: URL or Anon Key is missing!"); // Log error before throwing
  throw new Error("Supabase URL and Anon Key must be provided.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    // Automatically refreshes the session
    autoRefreshToken: true,
    // Persists the session locally
    persistSession: true,
    // Detects session changes across tabs
    detectSessionInUrl: true, 
  },
});
