// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhqydbtxaxmxradkdwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aHF5ZGJ0eGF4bXhyYWRrZHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mzc1MjAsImV4cCI6MjA2MDQxMzUyMH0.QPHbCGSjwRA-Ni74y7EL292KXzxh8ftLAp1AILLaYu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);